name: spotlight
description: "A Flutter plugin to highlight a spotlight effect."
homepage: https://github.com/sahilkakadiy/spotlight
#author: Sahil Kakadiya <sahilkakadiya67@gmail.com>
repository: https://github.com/sahilkakadiy/spotlight

version: 1.0.1

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass

#publish_to: 'https://pub.dev/'

